<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>UniversalConvert.Plugin.Ncm</RootNamespace>
    <AssemblyName>UniversalConvert.Plugin.Ncm</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UniversalConvert.Core\UniversalConvert.Core.csproj" />
  </ItemGroup>

</Project>
